---
title: "Scientific Instrumentation Table: Agilent Cary 3500 UV-Vis Flexible"
date: last-modified
format:
  html:
    toc: false
    css: styles.css
---

# Table Schema

| Field                          | Value |
|--------------------------------|-------|
| Instrument_Name                |  Agilent Cary 3500 UV-Vis Flexible     |
| Instrument_Acquisition_Date    |  2025-08     |
| Instrument_CommonName          |  UV-Vis Spec     |
| Instrument_Manufacturer        |  [Agilent](https://www.agilent.com/)     |
| Instrument_Model               | [Agilent Cary 3500 UV-Vis Flexible](https://www.agilent.com/en/product/molecular-spectroscopy/uv-vis-uv-vis-nir-spectroscopy/uv-vis-uv-vis-nir-systems/cary-3500-flexible-uv-vis-spectrophotometer)      |
| Instrument_Serial#             | [MY2517ZA05](/assets/images/Agilent-Cary-3500-UV-Vis-Flexible_SerialNumber.jpg)      |
| Instrument_Asset_Tag           |  NA     |
| Instrument_MAC                 |       |
| Instrument_IP                  |       |
| Instrument_TurnKeySolution     |       |
| Instrument_Roaming             |  No     |
| Instrument_Building            |  Lab I     |
| Instrument_Floor               |  2     |
| Instrument_Room                |  2035     |
| Computer_Hostname              |  SC-A-Cary-3500     |
| Computer_IP                    |  DHCP     |
| Computer_MAC                   |  AC-B4-80-FE-9E-0F     |
| Computer_Make                  |  Dell     |
| Computer_Model                 |  Pro Max Tower T2 FCT2250     |
| Computer_Asset_Tag             |  14493     |
| Computer_OS                    |  Windows 11     |
| Computer_OS_Version            |  24H2     |
| Computer_RAM                   |  16 GB     |
| Computer_HD                    |       |
| Software_Vendor                |  Agilent     |
| Software_Product_Name          |  OpenLab     |
| Software_Version               |       |
| Software_Last_Updated_Date     |  2025-10     |

: Table {.bordered .hover}